### ISSUE TITLE
All SwitchBot devices unavailable on Home Assistant

### ISSUE THREAD

**Issue by EAuckland** [OpenWonderLabs/SwitchBotAPI#276]
### Current Situation

After updating to Home Assistant 2024.1, all SwitchBot devices became unavailable and unresponsive via Home Assistant.

### Logs

```markdown
2024-01-23 18:29:45.714 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Maggie's Curtain for switchbot
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/switchbot/__init__.py", line 102, in async_setup_entry
await switchbot.close_stale_connections_by_address(address)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'switchbot' has no attribute 'close_stale_connections_by_address'

Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: January 21, 2024 at 09:46:51 (12 occurrences)
Last logged: 18:29:45

Error setting up entry Basement Blinds Left for switchbot
Error setting up entry Basement Blinds Right for switchbot
Error setting up entry Office Curtain for switchbot
Error setting up entry Eddie's Curtain for switchbot
Error setting up entry Maggie's Curtain for switchbot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/switchbot/__init__.py", line 102, in async_setup_entry
    await switchbot.close_stale_connections_by_address(address)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'switchbot' has no attribute 'close_stale_connections_by_address'
```

### Configuration

```json
N/A
```

### Environment

- OS: HAOS 11.4
- Software: Home Assistant 2024.1.5
- Node: N/A
- npm: N/A

**Comment by donavanbecker** [comment]
This repo only lays out the api, you will need to reach out to home assistant for support on their integration.

**Comment by EAuckland** [comment]
> This repo only lays out the api, you will need to reach out to home assistant for support on their integration.

ok, thank you!
