### ISSUE TITLE
Intermittent 500 internal server errors

### ISSUE THREAD

**Issue by chrisg30** [OpenWonderLabs/SwitchBotAPI#286]
### Current Situation

I'm using Home Assistant with the Switchbot Cloud API integration. Up until the last couple of weeks, all was well but recently I've been seeing automations failing intermittently. I'd say 95% of the time they fire normally.

Can you help me understand why I'm seeing these errors more recently?

I have, of course, performed the obligatory router reboot.

### Logs

```markdown
2024-02-01 02:27:13.321 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-01 05:04:08.655 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-02 16:56:10.417 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-04 09:10:04.601 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-05 07:30:03.999 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-05 15:30:03.061 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-05 15:30:03.259 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-05 17:53:03.260 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-06 03:48:48.860 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-06 06:16:06.861 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-06 18:50:05.072 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-06 19:32:03.974 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-07 06:32:25.934 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-08 00:06:03.181 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-08 00:51:21.389 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-08 01:20:03.223 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-08 03:15:21.446 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-08 05:10:04.576 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-08 07:30:02.702 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-09 13:56:52.189 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-09 15:21:42.323 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-09 15:30:02.660 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-10 01:28:23.816 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-10 06:10:02.632 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-10 18:10:03.446 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-11 05:59:05.886 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-12 04:24:27.844 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-12 07:30:03.130 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-12 10:16:05.552 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-12 10:20:27.769 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-12 11:11:10.778 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-12 12:45:27.601 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-12 15:38:07.182 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-12 18:16:08.173 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-13 15:25:03.978 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-13 19:39:25.945 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-13 20:55:03.709 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-14 02:00:25.297 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-14 13:20:23.741 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-14 19:58:04.625 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-15 01:03:26.479 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-15 05:28:29.728 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-16 23:10:03.346 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-17 11:38:38.881 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-17 13:10:56.918 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-18 00:22:52.890 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-18 09:26:37.703 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-19 02:04:56.741 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-19 03:04:37.940 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-19 17:00:02.285 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-19 20:10:03.008 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-21 01:29:04.089 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-21 07:30:04.516 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-22 05:15:04.101 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-23 05:00:38.303 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-23 06:01:02.209 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-23 08:23:52.562 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-24 18:10:32.764 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-25 22:00:03.132 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-26 07:30:03.107 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-26 19:00:01.936 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-26 19:21:26.401 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-27 06:42:12.286 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-27 07:30:03.163 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-27 15:30:01.696 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-27 15:30:03.808 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-28 02:16:02.038 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-28 17:00:02.147 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-28 23:58:01.847 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-29 00:00:03.722 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-29 07:30:03.994 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-29 08:50:06.021 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-29 09:00:08.867 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-29 15:30:02.510 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-29 15:30:02.799 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-02-29 21:05:19.481 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-01 01:16:01.948 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-01 02:34:01.891 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-01 06:34:02.099 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-01 06:34:44.827 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-01 11:35:09.439 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-01 13:28:07.245 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-01 22:28:09.661 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-02 00:22:02.371 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-02 01:45:16.093 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-02 02:25:15.902 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-02 05:25:17.601 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-02 08:16:04.655 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-02 08:19:03.382 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-02 16:50:04.001 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-02 20:30:05.838 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-03 00:50:02.548 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-03 02:07:42.604 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-03 03:07:31.803 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-03 04:50:04.441 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-03 05:26:15.314 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-03 05:30:45.350 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-03 09:52:02.522 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-03 10:02:07.871 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-03 12:32:04.362 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-03 15:39:04.288 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-03 15:53:03.868 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-03 16:35:55.855 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-03 17:00:01.735 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-03 22:42:03.639 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-04 03:00:03.937 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-04 04:18:38.030 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-04 05:24:03.593 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-04 05:42:45.994 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-04 06:53:59.982 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-04 07:13:33.103 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-04 07:30:02.690 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-04 09:02:03.266 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-04 10:08:07.223 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-04 10:51:35.710 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-04 12:10:25.181 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-04 15:30:01.635 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-04 18:25:07.512 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-05 01:20:04.427 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-05 02:18:40.809 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-05 02:37:02.977 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-05 05:10:09.022 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-05 07:30:01.616 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-05 08:31:06.705 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-05 15:29:12.454 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-05 21:30:03.681 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-05 22:22:02.896 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-06 00:54:02.871 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-06 03:57:12.842 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-06 09:44:47.908 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-06 18:44:49.646 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-06 20:19:05.617 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-07 05:08:06.685 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-07 07:30:02.148 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-07 15:22:17.233 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-07 18:31:25.005 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-07 19:38:04.080 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-08 00:00:06.390 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-08 02:34:06.874 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-08 02:56:58.317 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-08 04:11:06.802 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-08 05:05:44.415 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-08 07:40:44.658 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-08 11:01:20.575 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-08 12:08:09.216 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-09 02:31:37.795 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-09 04:16:04.066 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-09 05:28:08.332 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-09 07:15:03.950 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-09 07:26:04.030 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-09 07:46:10.021 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-09 08:45:08.264 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-09 09:28:03.899 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-09 10:39:52.235 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-09 12:11:04.261 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-09 12:48:05.801 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-09 16:52:07.520 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-10 00:58:05.279 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-10 01:15:15.501 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-10 04:11:03.587 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-10 09:41:21.437 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-10 09:55:21.445 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-10 11:52:32.172 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-10 12:55:08.308 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-10 19:00:04.116 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-11 04:48:42.002 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-11 05:14:45.949 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-11 07:30:03.862 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-11 13:07:27.051 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-11 22:34:04.878 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-12 00:26:01.936 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-12 02:00:08.524 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-12 04:09:12.990 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-12 06:12:23.952 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-12 06:55:36.132 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-12 07:30:02.586 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-12 11:39:09.848 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-12 15:16:57.748 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-13 03:26:37.441 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-13 03:29:07.710 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-13 05:11:13.397 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-13 07:11:13.365 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-13 07:30:02.303 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-13 07:59:01.430 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-13 10:58:05.270 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-13 17:08:07.385 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-13 17:08:07.628 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-13 18:51:07.916 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-14 07:30:03.514 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-14 09:03:02.080 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-14 16:16:05.822 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-14 16:40:03.607 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-14 18:00:02.715 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}
2024-03-14 19:16:04.975 ERROR (MainThread) [switchbot_api] Error 500: {'message': 'Internal server error'}

It's always the same traceback:

2024-03-15 06:38:08.390 ERROR (MainThread) [homeassistant.components.automation.lr_heat_on_work] Heat LR On: Error executing script. Unexpected error for device at pos 1:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 720, in _async_device_step
    await device_action.async_call_action_from_config(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/action.py", line 71, in async_call_action_from_config
    await platform.async_call_action_from_config(hass, config, variables, context)
  File "/usr/src/homeassistant/homeassistant/components/switch/device_action.py", line 35, in async_call_action_from_config
    await toggle_entity.async_call_action_from_config(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/toggle_entity.py", line 123, in async_call_action_from_config
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/switchbot_cloud/switch.py", line 40, in async_turn_on
    await self.send_command(CommonCommands.ON)
  File "/usr/src/homeassistant/homeassistant/components/switchbot_cloud/entity.py", line 44, in send_command
    await self._api.send_command(
  File "/usr/local/lib/python3.11/site-packages/switchbot_api/__init__.py", line 226, in send_command
    await self._request_device(f"{device_id}/commands", callback="post", json=json)
  File "/usr/local/lib/python3.11/site-packages/switchbot_api/__init__.py", line 177, in _request_device
    raise CannotConnect()
switchbot_api.CannotConnect
```

### Configuration

```json
Example HA automation:

alias: Heat LR On
description: ""
trigger:
  - type: temperature
    platform: device
    device_id: 1d4c6d927432e0af320e0252e9734a70
    entity_id: 6d07edd2c9b85d1bdf46692f89018531
    domain: sensor
    below: 19.3
    for:
      hours: 0
      minutes: 1
      seconds: 0
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
      - input_boolean.saving_session
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 10
  - type: temperature
    platform: device
    device_id: 1d4c6d927432e0af320e0252e9734a70
    entity_id: 6d07edd2c9b85d1bdf46692f89018531
    domain: sensor
    below: 19
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: time
    at: "17:00:00"
  - type: temperature
    platform: device
    device_id: 1d4c6d927432e0af320e0252e9734a70
    entity_id: 6d07edd2c9b85d1bdf46692f89018531
    domain: sensor
    below: 18.8
    for:
      hours: 0
      minutes: 0
      seconds: 0
condition:
  - type: is_temperature
    condition: device
    device_id: 1d4c6d927432e0af320e0252e9734a70
    entity_id: 6d07edd2c9b85d1bdf46692f89018531
    domain: sensor
    below: 19.3
  - condition: state
    entity_id: input_boolean.saving_session
    state: "off"
action:
  - type: turn_on
    device_id: 7f36312f97dc6a87faf3aa700cbf429f
    entity_id: cdf8c8911dfa0da479b0a97192a93c4b
    domain: switch
    continue_on_error: true
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
    enabled: true
  - if:
      - condition: and
        conditions:
          - condition: time
            after: "08:00:00"
            before: "23:00:00"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
              - sat
              - sun
          - condition: state
            entity_id: switch.lr_heat_19c
            state: "on"
    then:
      - type: turn_off
        device_id: 7f36312f97dc6a87faf3aa700cbf429f
        entity_id: cdf8c8911dfa0da479b0a97192a93c4b
        domain: switch
        continue_on_error: true
    enabled: true
mode: single
```

### Environment

Home Assistant 2023.10.3
Supervisor 2024.03.0
Operating System 10.5

**Comment by MrXANA91** [comment]
I am also having this issue from time to time using custom and official integrations for HomeAssistant

Issue mentionned in this [Homeseer plugin thread](https://forums.homeseer.com/forum/hs4-products/hs4-plugins/lighting-primary-technology-plug-ins-aa/ak-switchbot/1659062-the-remote-server-returned-an-error-500-internal-server-error) as well

**Comment by chrisg30** [comment]
Anyone able to look at this please?

**Comment by wcwynn** [comment]
Also experiencing intermittent failures:

-  receiving intermittent 500s sending device control commands and reading status:
    - POST /v1.1/devices/{deviceId}/commands
    - GET /v1.1/devices/{deviceId}/status

- [webhook events](https://github.com/OpenWonderLabs/SwitchBotAPI/blob/main/README.md#receive-events-from-webhook) in response to successful device control command are intermittently not sent❗ 

**Failure Rate for POST/GET:**
- ~95% of the time the POST/GET is OK
- ~5% of the time POST/GET fails with 500

**Missing webhook callback Rate:**
- ~95% of the time after successful POST webhook is received
- ~5% of the time after successful POST webhook is NOT received

**Comment by chrisg30** [comment]
6 weeks in, no comments from dev. Really? Is this the customer experience we're to expect? How hard is it to investigate and increase the API limit, if that's what the issue is?

**Comment by chrgan** [comment]
I'm having issues which I think are related to this. I'm running a python script on a raspberry pi which checks for humidity (SwitchBot Indoor/Outdoor Thermo-Hygrometer, SwitchBot Hub Mini), turns on a ventilator when the humidity is above a certain threshold with a switchbot bot, sleeps for some time and then turns the ventilation off again. This worked without problems for months now, but since last Friday, the ventilation isn't turned off reliably any more. Error:  SwitchBot API server returns status 500. Since I didn't change anything and the command occasionally runs successful (turning on seems to always succeed), I suspect some problems on the server.

**Comment by longnguyenandpadcojp** [comment]
I've faced same issue. Is there any clue or solution?

**Comment by chrgan** [comment]
I let my script resend the command in case it doesn't succeed.

```python
while True:
    try:
        time.sleep(5)
        switchklbad.command('turn_off')
    except:
        continue
    else:
        break
``` 
(I suspect the except statement should be more specific, but it works.)

**Comment by strunker** [comment]
I too am struggling with this problem, just hadn't bothered to comment until now. Switchbot rarely replies to any of the threads here. So for those expecting some kind of response, I wouldn't. They once commented, "we focus on new product support", not really on new features to existing, and apparently not bug fixes or service degradations. It is rather annoying though. I have a thread that runs and pulls all my devices and their respective status to get the battery level (which is often not accurate, but that is a story for another time), you can see sporadically and only on certain devices do I get the error when doing /status. 

SwitchBot Devices:
SwitchBot Get Status Error: Bedroom Curtain - 500
SwitchBot Get Status Error: Door - 500
Laptop - 99% Battery
Hub  - 55% Humidity | 62.42 Degrees | 1 Light Level
Living Room Curtain - 91% Battery
TV (01-202305131201-42881787)
Living Room Air Conditioner (01-202305131203-15128740)
Speaker (01-202305131210-91677071)
Loft Air Conditioner (01-202405011946-51917202)
Bed TV (01-202405020056-74445337)

**Comment by MrXANA91** [comment]
The only quickfix I can think of for now is to wait for the server response and try again in case of error status 500, with limited tries of course (3 should be enough).

I saw there was a maintenance plan around a week ago, I don't know if this was aimed to solve this issue in particular.

**Comment by longnguyenandpadcojp** [comment]
Thanks,  for time being, only solution is retry

**Comment by chrisg30** [comment]
Thank you @chrgan - your workaround is helping greatly!
