### ISSUE TITLE
POST command using axios returns code 401

### ISSUE THREAD

**Issue by mj1241** [OpenWonderLabs/SwitchBotAPI#92]
**Describe The Bug:**

Using Axios and NodeJs, I can GET list of device and device status using an authentication code, but with POST command to device, using same authentication code results to code 401

**To Reproduce:**

Using the code below:
```
app.get("/postDevicesCommand", (req, res) => {
    let listDeviceCmd = "https://api.switch-bot.com/v1.0/devices/"
    let auth = "d698192195a04cf2667f41df22ee93fed3bd8668ab9e81230a1e51245d4ce63c4378e45fbfb24e8406426ede55be6130"

    listDeviceCmd = listDeviceCmd + "DE9D7A7B5AEF" + "/commands"
    
    // listDeviceCmd = listDeviceCmd + req.query.deviceID + "/commands"
    const axios = require("axios");

    // let obj = {'command':'turnOn', 'parameter':'default', 'commandType': 'command'}
    console.log(listDeviceCmd)
    axios.post(listDeviceCmd,{
        mode: 'no-cors',
        headers: {'Authorization': auth, 'Content-Type': 'application/json; charset=utf8'},
        data: {command:'turnOn'},
        // withCredentials: false, // default
        // auth: false,
        // headers: {'Authorization': auth},
        // data:JSON.stringify({command:'turnOn'}),
        // command:'turnOn',
        }).then(result => {
            console.log(result.data.body)
        }).catch(error => {
            console.log(error)
        })
        

});
```

**results to:**
```
server running on port3001
https://api.switch-bot.com/v1.0/devices/DE9D7A7B5AEF/commands
Error: Request failed with **status code 401**
    at createError (C:\Users\mjavier\OneDrive - Lenovo\Desktop\PCP Exit\lilikoi\backend_server\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\mjavier\OneDrive - Lenovo\Desktop\PCP Exit\lilikoi\backend_server\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\mjavier\OneDrive - Lenovo\Desktop\PCP Exit\lilikoi\backend_server\node_modules\axios\lib\adapters\http.js:322:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.26.1',
      'Content-Length': 221
    },
    method: 'post',
    url: 'https://api.switch-bot.com/v1.0/devices/DE9D7A7B5AEF/commands',
    data: '{"mode":"no-cors","headers":{"Authorization":"d698192195a04cf2667f41df22ee93fed3bd8668ab9e81230a1e51245d4ce63c4378e45fbfb24e8406426ede55be6130","Content-Type":"application/json; charset=utf8"},"data":{"command":"turnOn"}}'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.switch-bot.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.switch-bot.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 17,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST /v1.0/devices/DE9D7A7B5AEF/commands HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'User-Agent: axios/0.26.1\r\n' +
      'Content-Length: 221\r\n' +
      'Host: api.switch-bot.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/v1.0/devices/DE9D7A7B5AEF/commands',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 401,
      statusMessage: 'Unauthorized',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api.switch-bot.com/v1.0/devices/DE9D7A7B5AEF/commands',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.switch-bot.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 221,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.switch-bot.com/v1.0/devices/DE9D7A7B5AEF/commands',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    }
  },
  response: {
    status: 401,
    statusText: 'Unauthorized',
    headers: {
      date: 'Tue, 05 Apr 2022 07:00:08 GMT',
      'content-type': 'application/json',
      'content-length': '26',
      connection: 'close',
      'x-amzn-requestid': '85acb55d-fd79-4481-a1cf-18e2cc025541',
      'x-amzn-errortype': 'UnauthorizedException',
      'x-amz-apigw-id': 'QGFW5EUlIAMFvqw='
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'post',
      url: 'https://api.switch-bot.com/v1.0/devices/DE9D7A7B5AEF/commands',
      data: '{"mode":"no-cors","headers":{"Authorization":"d698192195a04cf2667f41df22ee93fed3bd8668ab9e81230a1e51245d4ce63c4378e45fbfb24e8406426ede55be6130","Content-Type":"application/json; charset=utf8"},"data":{"command":"turnOn"}}'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /v1.0/devices/DE9D7A7B5AEF/commands HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.26.1\r\n' +
        'Content-Length: 221\r\n' +
        'Host: api.switch-bot.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v1.0/devices/DE9D7A7B5AEF/commands',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.switch-bot.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { message: 'Unauthorized' }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

**but using same device id, and authentication key, but using GET status instead:**

```app.get("/getDevicesStatus", (req, res) => {
    let listDeviceCmd = "https://api.switch-bot.com/v1.0/devices/"
    let auth = "d698192195a04cf2667f41df22ee93fed3bd8668ab9e81230a1e51245d4ce63c4378e45fbfb24e8406426ede55be6130"

    listDeviceCmd = listDeviceCmd + "DE9D7A7B5AEF" + "/status"
    const axios = require("axios");

    console.log(listDeviceCmd)
    axios.get(listDeviceCmd,{
        // headers: {'Content-Type': "application/json; charset=utf8" ,'Authorization': auth}
        mode: 'no-cors',
        headers: {'Authorization': auth},
        }).then(result => {
            console.log(result.data.body)
        })

});

```

results to:
```
![image](https://user-images.githubusercontent.com/102502901/161697917-787ed7c8-c2c5-4275-984d-a457eaceb1b1.png)

```

**Expected behavior:**

**Screenshots:**

**Device Model:**

Hub Mini and SwitchBot Bot

# **SwitchBotAPI**
- **Use Case**:

Send POST command to SwitchBot bot using OpenWonderLabs Switchbot API

**Comment by AdyRock** [comment]
Not sure if this will help, but have you enabled cloud access to the device in the SwitchBot app?

**Comment by mj1240** [comment]
Sorry, I was able to fix the problem by using fetch instead of axios.

Though I did not really found the root cause.
